.TH "FRESHBOOKS\-TIMETRAP" "" "May 2014" "" ""
.SH "NAME"
\fBfreshbooks-timetrap\fR
.QP
.P
Integrates the freshbooks\-cli tools with timetrap time tracking

.
.SH Usage
.P
.RS 2
.EX
\-\-lines, \-l \- Convert timetrap entries to JSON\-formatted invoice lines

\-\-data JSON \- Time entry data for \-\-create

\-\-help, \-h \- Display this message
.EE
.RE
.P
See http://developers\.freshbooks\.com/docs/invoices/#invoice\.lines\.add for more information\.
.SH Examples
.P
.RS 2
.EX
# Converting timetrap entries into invoice line items
$ timetrap display \-s saturday \-e friday \-f json | freshbooks timetrap \-\-lines
[
  {
    "name":"Some task",
    "description":"Did some work",
    "unit_cost":"150",
    "quantity":"3\.2",
    "type":"Item"
  },
  {
    "name":"Some task",
    "description":"Did some other work",
    "unit_cost":"150",
    "quantity":"0\.0",
    "type":"Item"
  },
  {
    "name":"Some task",
    "description":"Did some different work",
    "unit_cost":"150",
    "quantity":"0\.5",
    "type":"Item"
  }
]
.EE
.RE